### ISSUE TITLE
Do I need to propose a standard here?

### ISSUE THREAD

**Issue by poria-cat** [w3f/PSPs#15]
Hi @Noc2, I am very happy to say that my work has basically been completed, but after the development is complete, the initial Sub NFT has become a multifunctional NFT. It includes batch minting/transfer, token combination method and splite method. In addition, I also added a reference to moloch's DAO, but you can use nft as a tribute. Do I need to mention here Is the multifunctional NFT standard part of Grant? Or is it just a token split standard?

**Comment by Swader** [comment]
Hi, can you go into more detail?
I'm from the RMRK team and it seems like there might be some overlap in features. What's this pertaining to, which grant, and where can we see the code?

**Comment by poria-cat** [comment]
Hi @Swader grant at here https://github.com/w3f/Open-Grants-Program/pull/233, Not open for now as some updates to the batch mint are needed.
