### ISSUE TITLE
[Question] FRAME Pallet Proposals

### ISSUE THREAD

**Issue by danforbes** [w3f/PSPs#9]
I have written [a FRAME pallet for non-fungible tokens](https://github.com/danforbes/pallet-nft) and am looking for feedback - is this the right place to have such a discussion?

**Comment by Noc2** [comment]
Yes, it is. At least if you want to create an NFT standard. Also feel free to join the riot channel and in general to contribute to the repo.  At the moment, no one is really responsible for this repo.
